/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       App_21266659_MesiasSozap classUnderTest = newApp_21266659_MesiasSozap();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
